
name: communication_app
description: A cross-platform communication app.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add authentication and SDK packages here
  # firebase_auth: ^3.3.19
  # flutter_facebook_auth: ^5.0.6
  # google_sign_in: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
